### PR TITLE
fix: dockerfileContent.ts & cleared *.sh files

### LINKED ISSUE #131: Stencil Base Project Cleanup
## P0
- [x] General Cleanup
    - [x] Remove `startup.*.sh` - P0
    - [x] Remove `wait-for-it.sh` - P0

- [x] Dockerfiles - [Refer](https://github.com/Samagra-Development/VISTAAR/blob/main/Dockerfile)
    - [x] Remove `e2e.Dockerfile` - P0
    - [x] Rewrite the `Dockerfile` and `Dockerfile.devcontainer` - P0

- [ ] Docker Compose Setup
    - [ ] Remove docker compose from the root and move to `/services` - PO
    - [ ] Update `docker-start.sh`
    - [ ] Add relevant commands in `package.json`

- [x] Husky Updates
    - [x] Add command for checking, fixing code formatting in precommit hooks. - P0
    - [x] Run `build` script and make sure that the code is building
    - [x] Run tests

## P1
- [ ] Update the github action workflows to also run the formatter and linter

### PR DESCRIPTION
**Pull request by shivankurchavan**
## PR Checklist
- [x] General cleanup 
  - [x] Removed ' *.sh ' files 
- [x] Docker files 
  - [x] Removed 'e2e.dockerfile'
  - [x] Rewritten 'Dockerfile'  and ' Dockerfile.devcontainer'
- [ ] Docker compose setup 
  - [ ] Remove docker compose from root and add it to '/services' 
  - [ ] Update 'docker-start.sh'
  - [ ] Add relevant commands in 'package.json'
- [x] Updated husky pre-commit

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

### CODE REVIEW

File: src/lib/fixtures/dockerfileContent.ts [hunk 1]
```diff
@@ -1,22 +1,26 @@
...
+# Copy the package.json and package-lock.json files to the container
+COPY package*.json ./
 
-COPY . /usr/src/app
-RUN cp -a /tmp/app/node_modules /usr/src/app
-COPY ./wait-for-it.sh /opt/wait-for-it.sh
-COPY ./startup.dev.sh /opt/startup.dev.sh
-RUN sed -i 's/\r//g' /opt/wait-for-it.sh
-RUN sed -i 's/\r//g' /opt/startup.dev.sh
+RUN npm i -g @nestjs/cli @samagra-x/stencil-cli typescript ts-node
```
Comment (techsavvyash) [inline src/lib/fixtures/dockerfileContent.ts]: don't install both clis it will cause a lot of conflicts in commands

File: src/lib/fixtures/dockerfileContent.ts [hunk 2]
```diff
@@ -1,22 +1,26 @@
...
-RUN cp env-example .env
-RUN npx prisma generate 
+# Install dependencies
+RUN npm install
+
+# Copy the rest of the application code to the container
+COPY . .
+
+# Build the NestJS application
+RUN npx prisma generate
```
Comment (techsavvyash) [inline src/lib/fixtures/dockerfileContent.ts]: why are we always including `npx prisma generate` what is the user has not even opted for prisma setup? this will cause a lot of trouble.

File: src/lib/fixtures/dockerfileContent.ts [hunk 3]
```diff
@@ -1,22 +1,26 @@
...
 RUN npm run build
 
-CMD ["/opt/startup.dev.sh"]
+# Expose the port the app runs on
+EXPOSE 3000
```
Comment (techsavvyash) [inline src/lib/fixtures/dockerfileContent.ts]: make this PORT configurable via environment variables.

File: src/lib/fixtures/dockerfileContent.ts [hunk 4]
```diff
@@ -1,22 +1,26 @@
...
+
+CMD ["npm", "run", "start:dev"]
```
Comment (techsavvyash) [inline src/lib/fixtures/dockerfileContent.ts]: take the development environment as a input from env and based on that run the commands. for example if the environment is `DEVELOPMENT` then do `start:dev` else if the env is `PRODUCTION` run `start:prod`

File: src/lib/fixtures/files/ts/Dockerfile [hunk 5]
```diff
@@ -1,21 +1,25 @@
...
+# Use an official Node.js runtime as a parent image 
+
+# Set the working directory in the container
+WORKDIR /usr/src/app
+
+# Copy the package.json and package-lock.json files to the container
+COPY package*.json ./
 
-RUN apk add --no-cache bash
 RUN npm i -g @nestjs/cli @samagra-x/stencil-cli typescript ts-node
```
Comment (techsavvyash) [inline src/lib/fixtures/files/ts/Dockerfile]: don't install both CLIs.

File: src/lib/fixtures/files/ts/Dockerfile [hunk 6]
```diff
@@ -1,21 +1,25 @@
...
-RUN sed -i 's/\r//g' /opt/wait-for-it.sh
-RUN sed -i 's/\r//g' /opt/startup.dev.sh
+# Copy the rest of the application code to the container
+COPY . .
 
-WORKDIR /usr/src/app
-RUN cp env-example .env
-RUN npx prisma generate 
+# Build the NestJS application
+RUN npx prisma generate
```
Comment (techsavvyash) [inline src/lib/fixtures/files/ts/Dockerfile]: this will not be there always.

File: src/lib/fixtures/files/ts/Dockerfile [hunk 7]
```diff
@@ -1,21 +1,25 @@
...
 RUN npm run build
 
-CMD ["/opt/startup.dev.sh"]
+# Expose the port the app runs on
+EXPOSE 3000
+
+CMD ["npm", "run", "start:dev"]
```
Comment (techsavvyash) [inline src/lib/fixtures/files/ts/Dockerfile]: make this configurable.

File: src/lib/fixtures/files/ts/Dockerfile [hunk 8]
```diff
@@ -1,21 +1,25 @@
...
-WORKDIR /usr/src/app
-RUN cp env-example .env
-RUN npx prisma generate 
+# Build the NestJS application
+RUN npx prisma generate
 RUN npm run build
 
-CMD ["/opt/startup.dev.sh"]
+# Expose the port the app runs on
+EXPOSE 3000
```
Comment (techsavvyash) [inline src/lib/fixtures/files/ts/Dockerfile]: make this as a env var.

File: src/lib/fixtures/files/ts/Dockerfile.devcontainer
Comment (techsavvyash) [inline src/lib/fixtures/files/ts/Dockerfile.devcontainer:1]: same changes as the dockerfile.

**Review by techsavvyash — CHANGES_REQUESTED** [review]

File: src/lib/fixtures/dockerfileContent.ts (hunk 1 above)
Comment (shivankurchavan) [reply src/lib/fixtures/dockerfileContent.ts]: okay, so ill just keep @samagra-x/stnecil-cli ?

Comment (techsavvyash) [reply src/lib/fixtures/dockerfileContent.ts]: Yes

Comment (techsavvyash) [inline src/lib/fixtures/dockerfileContent.ts]: we are still installing both CLIs, please make it only one.

File: package.json [hunk 9]
```diff
@@ -24,7 +24,8 @@
     "test:dev": "NODE_ENV=test npm run -s test -- --watchAll",
     "prerelease": "npm run build",
     "release": "release-it",
-    "prepare": "husky install"
+    "prepare": "husky install",
+    "prettier": "prettier '{src,test}/**/*.ts' --watch ."
```
Comment (techsavvyash) [inline package.json]: why do we need this when we already have the `format` and `lint` commands?

File: src/lib/fixtures/dockerfileContent.ts (hunk 2 above)
Comment (techsavvyash) [inline src/lib/fixtures/dockerfileContent.ts]: why is it still there?

File: src/lib/husky/pre-commit.ts [hunk 10]
```diff
@@ -1,7 +1,15 @@
...
 
-npm run lint
+# Run Prettier to check and fix code formatting
+npm run prettier 
+
+# Run ESLint to check and fix code issues
+npm run lint 
+
+# Stage changes made by Prettier and ESLint
+git add .
```
Comment (techsavvyash) [inline src/lib/husky/pre-commit.ts]: why do we have it here? we discussed on the call to not have it here.

File: src/lib/fixtures/dockerfileContent.ts (hunk 3 above)
Comment (techsavvyash) [inline src/lib/fixtures/dockerfileContent.ts]: this is not resolved.

File: src/lib/fixtures/dockerfileContent.ts (hunk 4 above)
Comment (techsavvyash) [inline src/lib/fixtures/dockerfileContent.ts]: this is also not resolved.

File: src/lib/fixtures/files/ts/Dockerfile [hunk 11]
```diff
@@ -1,21 +1,29 @@
...
 
-CMD ["/opt/startup.dev.sh"]
+# Set environment variable (default value, can be overridden by .env)
+ENV PORT 3000
+ENV ENVIRONMENT DEVELOPMENT
+
+# Expose the port the app runs on
+EXPOSE ${PORT}
+
+CMD ["sh", "-c", "if [ \"$ENVIRONMENT\" = \"PRODUCTION\" ]; then npm run start:prod; else npm run start:dev; fi"]
```
Comment (techsavvyash) [inline src/lib/fixtures/files/ts/Dockerfile]: I think docker has native support for env vars via the projects root level `.env` files

**Review by techsavvyash — CHANGES_REQUESTED** [review]

File: src/lib/fixtures/files/ts/Dockerfile (hunk 11 above)
Comment (shivankurchavan) [reply src/lib/fixtures/files/ts/Dockerfile]: yes it has native support, we are setting default to 3000, can be overridden by `.env` file

**Review by techsavvyash — APPROVED** [review]
